config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'groups#index'
  resources :messages, only: [:index]
  resources :users, only: [:index, :edit, :update, :search]
  resources :groups, only: [:new, :create, :edit, :update] do
    resources :messages, only: [:index, :create]
    namespace :api do
      resources :messages, only: :index, defaults: { format: 'json' }
    end
  end
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :group
  belongs_to :user

  validates :content, presence: true, unless: :image?
  mount_uploader :image, ImageUploader

end

app/controllers/api/messages_controller.rb
class Api::MessagesController < ApplicationController
  def index
    # ルーティングでの設定によりparamsの中にgroup_idというキーでグループのidが入るので、これを元にDBからグループを取得する
    group = Group.find(params[:group_id])
    # ajaxで送られてくる最後のメッセージのid番号を変数に代入
    last_message_id = params[:id].to_i
    # 取得したグループでのメッセージ達から、idがlast_message_idよりも新しい(大きい)メッセージ達のみを取得
    @messages = group.messages.includes(:user).where("id > #{last_message_id}")
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_group

  def index
    @message = Message.new
    @messages = @group.messages.includes(:user)
  end

  def create
    @message = @group.messages.new(message_params)
    respond_to do |format|
      if @message.save
        format.html { redirect_to group_messages_path(@group), notice: 'メッセージが送信されました' }
        format.json
      else
        @messages = @group.messages.includes(:user)
        flash.now[:alert] = 'メッセージを入力してください。'
        render :index
      end
    end
  end

  private

  def message_params
    params.require(:message).permit(:content, :image).merge(user_id: current_user.id)
  end

  def set_group
    @group = Group.find(params[:group_id])
  end
end

app/views/messages/_message.html.haml
.message{"data-message-id": "#{message.id}"}
  .upper-message
    .upper-message__user-name
      = message.user.name
    .upper-message__date
      = message.created_at.strftime("%Y/%m/%d %H:%M")
  .lower-message
    - if message.content.present?
      %p.lower-message__content
        = message.content
    = image_tag message.image.url, class: 'lower-message__image' if message.image.present?

app/views/messages/index.html.haml
%div.wrapper

  = render 'shared/side_bar'

  %div.chat-main
    %div.main-header
      %div.main-header__left-box
        %p.main-header__left-box__group-name
          = @group.name
        %p.main-header__left-box__group-members
          Member：
          - @group.users.each do |user|
            = user.name
      %div.main-header__edit-btn
        = link_to edit_group_path(@group) do
          %p EDIT

    %div.messages
      = render @messages
      -# 省略前
      -# = render partial: 'message', collection: @messages

    %div.form-wrapper
      %div.form
        = form_for [@group, @message] do |f|
          = f.text_field :content, class: 'form__message', placeholder: 'type a message'
          .form__mask
            = f.label :image, class: 'form__mask__image' do
              = fa_icon 'picture-o', class: 'icon'
              = f.file_field :image, class: 'hidden'
          = f.submit 'Send', class: 'form__submit'